version: '3.8'

services:
  main-app:
    build: ./app
    container_name: main-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SIGNAL_SERVICE_URL=http://signal-service:5001
    networks:
      - app-network
    depends_on:
      - signal-service
    restart: unless-stopped

  signal-service:
    build: ./signal_processing_service
    container_name: signal-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production