version: '3.8'

services:
  main-app:
    image: homerwork4.azurecr.io/main-app:latest
    build: ./app
    container_name: main-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SIGNAL_SERVICE_URL=http://signal-service:5001
    networks:
      - app-network
    depends_on:
      - signal-service
    restart: unless-stopped

  signal-service:
    image: homerwork4.azurecr.io/signal-service:latest
    build: ./signal_processing_service
    container_name: signal-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

networks:
  app-network:  # Define the network
    driver: bridge